language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
notifications:
  slack: hr22-23:cj7Wc706h8pEu4BGApvLCuJc
# only run tests on master branch
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: r70l8i9mwh/5kbwdvcok+RpQvyhNHUKScMLuCD/1BtF45s5d0tXt2UbJNZuufdb5rLbBWlYE81/wZXNHXXJo0yaCQQCOyVfhRieyBzWmWjzqcaO5XgyKLUx39FZHPUJ/Eek39LqLSGPIBBOHUBFJvpsIWOvskHZMK/BgNnc4n+o=
  app: greenfield-tikr
  on:
    repo: tikr/tikr